Added lesson_5
yurachel/TMS-1101_2021 pull request #1
Opened 2021-01-26 11:44 UTC by yurachel

2021-01-29 17:19 UTC, RomanKashenok requested changes

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_10.java
> +        while (number < 16) {
I thought about one random number in range from 10 to 15, but all numbers in this range is fine too

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_11.java
> +        for (int i = 2; i < number; i++) {
ok. But cycle iterations could be less than from 2 to number. At least from 0 to number/2 (or even to sqrt(number))

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_12.java
> +        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
Why do you need Buffer here?

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_12.java
> +            if (i % 3 == 0) {
If I want to get sum of first 3 numbers that could be devided to 3, I'm expecting to get 18 as result, but not 3.

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_15.java
> +        s = array.length / 2;
let it be 
int s = array.length / 2

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Task_5.java
> +        for (int i = 2; i <= 100; i++) {
or just use i+=2;

2021-01-29 17:19 UTC, RomanKashenok commented on Tasks/Lesson_5/Task_6.java
> +        for (int i = 0; i < 100; i++) {
or just use 
i+=2 :)

2021-01-30 05:46 UTC, yurachel commented on Tasks/Lesson_5/Methodichka_12.java
> +            if (i % 3 == 0) {
From 1 to n we are founding simples numbers and than we find them sum

2021-01-30 05:46 UTC, yurachel commented on Tasks/Lesson_5/Methodichka_15.java
> +        s = array.length / 2;
ohh, yes int s = 0 is unnecessary

2021-01-31 15:40 UTC, JonDorian commented on Tasks/Lesson_5/Methodichka_17.java
> +        int count = n / 2;
Переменная count нигде не использована)

2021-01-31 19:31 UTC, JonDorian reviewed
Все вроде круто) Поправить по мелочи только, и все в огне))

2021-01-31 19:31 UTC, JonDorian commented on Tasks/Lesson_5/Task_3.java
> +        for (int i = 1; i <= 2564; i *= 2) {
Алгоритм работает правильно, и тут просто прикол(косяк) в самом задании на диске, там значение до 256 а 4 - это уже пошло новое задание, 4е)

2021-01-31 19:31 UTC, JonDorian commented on Tasks/Lesson_5/Task_3.java
> +        System.out.println("anotherCount is: " + anotherCount);
Для чего эти вычисления?) Ведь 3е задание уже сделано в верхнем for)

2021-01-31 19:31 UTC, JonDorian commented on Tasks/Lesson_5/Methodichka_17.java
> +        int count = n / 2;
Переменная count нигде не использована)

2021-02-01 04:57 UTC, yurachel commented on Tasks/Lesson_5/Task_3.java
> +        System.out.println("anotherCount is: " + anotherCount);
просто не понял смысла задания,и сделал и так и так)

2021-02-01 09:43 UTC, JonDorian approved these changes

2021-02-01 11:46 UTC, AlexandrKachan requested changes

2021-02-01 11:46 UTC, AlexandrKachan commented on Tasks/Lesson_5/Methodichka_17.java
>  }
С меня пиво за решение этой задачи)

2021-02-04 12:42 UTC, RomanKashenok requested changes

2021-02-04 12:42 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_12.java
> +            if (i % 3 == 0) {
Переформулирую по русски )) Нам нужно найти сумму первых N чисел, а не среди первых N чисел, вычислить сумму, делящихся на 3.

2021-02-04 12:42 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_11.java
> +                if (i == 0) continue;
это вообще как? i = 0, если i == 0 -> пропустить итерацию...

2021-02-04 12:42 UTC, RomanKashenok commented on Tasks/Lesson_5/Methodichka_11.java
> +                if (number % i == 0 && i!=1) {
тоже условие так себе. Ноль пропустили потому, что он ноль. Единицу пропустили потому, что она - единица...
идем снова от нуля, который вместе с единицей пропускаем, и до самого числа... В общем было не оптимально, а получилось еще сложнее и еще не оптимальнее...

2021-02-06 14:35 UTC, merged