Added 2 new tasks.
yurachel/TMS-1101_2021 pull request #6
Opened 2021-02-17 12:08 UTC by yurachel

Tasks from Blinov

2021-02-20 16:38 UTC, RomanKashenok requested changes

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_calendar/by/yurachel/calendar_task/entity/Calendar.java
> +    private Weekend weekends;
Итого у тебя один выходной, один какой-то главный праздник Holiday и целая коллекция каких-то еще праздников List<Calendar.Holiday> holidaysList?

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_calendar/by/yurachel/calendar_task/entity/Calendar.java
> +    public class Weekend {
зачем public? Как вообще это компилятор пропустил? Или ты даже не компилировал?

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_calendar/by/yurachel/calendar_task/logic/Add.java
> +public class Add {
Что за класс Add? метод добавления должен быть в календаре

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_calendar/by/yurachel/calendar_task/logic/Sort.java
> +public class Sort {
аналогично добавлению

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_calendar/by/yurachel/calendar_task/view/Show.java
> +public class Show {
Сделай класс CalendarUtils и туда запихни методы add, sort, show и что там еще придумаеш.

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_payment/by/yurachel/payment_task/entity/Payment.java
> +    public class Customer {
Не понимаю как у тебя в файле Payments могут быть несколько публичных классов...

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_payment/by/yurachel/payment_task/entity/Payment.java
> +    private Map<String, Integer> purchaseMap;
Map<String,Integer> - это что? У тебя зачем-то есть еще внешний класс Purchase. Помеяти его внутрь Payment и инкапсулируй информацию внутри него

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_payment/by/yurachel/payment_task/logic/Purchases.java
> +public class Purchases {
Класс должен быть внутренним для Payment

2021-02-20 16:38 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_payment/by/yurachel/payment_task/view/Show.java
> +public class Show {
Это тоже класс не сильно нужный

2021-02-21 06:00 UTC, yurachel commented on Tasks/lesson_11/task_from_blinov_payment/by/yurachel/payment_task/view/Show.java
> +public class Show {
Я прочитал где то,что нужно все по пакетам раскидывать,объекты отельно,логика, и так далее,и решил попробовать сделать так,видимо ерунда какая то).

2021-02-25 11:19 UTC, RomanKashenok approved these changes

2021-02-25 11:19 UTC, RomanKashenok commented on Tasks/lesson_11/task_from_blinov_calendar/by/yurachel/calendar_task/main/RunnerCalendar.java
> +        calendar.sortHolidays("Ascending");
лучше конечно для сортировки передавать не строку, а булен... Типа sortHolidays(true), а в самом метоже принимать так: sortHolidays(boolean isAscOrder);

2021-02-25 12:35 UTC, merged